on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'master'
    paths:
      - '.github'
      - 'platform'
      - 'script'
      - 'shared'
      - 'tests'
  push:
    branches:
      - '**'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
      - 'extras/**'
      - .dockerignore
      - .gitignore
      - CHANGELOG.md
      - Dockerfile
      - LICENSE
      - README.md

jobs:

  build_android:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: ["arm64", "x64"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java
        run: |
          echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV
          echo "$JAVA_HOME_17_X64/bin" >> $GITHUB_PATH
      - name: Setup Android NDK
        uses: android-actions/setup-android@v3
      - name: Install NDK
        run: sdkmanager "ndk;25.1.8937393"
      - name: Set NDK Home
        run: echo "ANDROID_NDK_HOME=${{ env.ANDROID_HOME }}/ndk/25.1.8937393" >> $GITHUB_ENV
      - name: Build Android ${{ matrix.arch }}
        run: python3 script/build.py --system android --arch ${{ matrix.arch }}
      - name: Package Android ${{ matrix.arch }}
        run: python3 script/package_platform.py --system android --arch ${{ matrix.arch }}
      - uses: actions/upload-artifact@v4
        with:
          name: android-${{ matrix.arch }}-jars
          path: target/skija-android-${{ matrix.arch }}-*


